export const AuditAction = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",

    SESSION_CREATED: "SESSION_CREATED",
    SESSION_UPDATED: "SESSION_UPDATED",
    SESSION_DELETED: "SESSION_DELETED",
    SESSION_BULK_DELETED: "SESSION_BULK_DELETED",
    SESSION_OVERRIDE_USED: "SESSION_OVERRIDE_USED",

    SUPERVISOR_IN_STORE_ADDED: "SUPERVISOR_IN_STORE_ADDED",
    SUPERVISOR_IN_STORE_REMOVED: "SUPERVISOR_IN_STORE_REMOVED",

    HOLIDAY_CREATED: "HOLIDAY_CREATED",
    HOLIDAY_UPDATED: "HOLIDAY_UPDATED",
    HOLIDAY_DELETED: "HOLIDAY_DELETED",

    CLINICIAN_CREATED: "CLINICIAN_CREATED",
    CLINICIAN_UPDATED: "CLINICIAN_UPDATED",

    ROOM_CREATED: "ROOM_CREATED",
    ROOM_UPDATED: "ROOM_UPDATED",

    USER_CREATED: "USER_CREATED",
    USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
    USER_DEACTIVATED: "USER_DEACTIVATED",
} as const;